language: node_js
node_js:
  - "14.9.0"
cache:
  yarn: true

script:
  - yarn run test:coveralls

before_deploy:
  - yarn run build

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
