export const GET_WEATHER_FORECAST_START = "GET_WEATHER_FORECAST_START";
export const GET_WEATHER_FORECAST_SUCCESS = "GET_WEATHER_FORECAST_SUCCESS";
export const GET_WEATHER_FORECAST_ERROR = "GET_WEATHER_FORECAST_ERROR";
